

name: deploy-and-notify
on:
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: centos-8
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: ./build.sh
      - name: Deploy to testing environment
        run: ./deploy.sh
        if: success()
      - name: Notify Microsoft Teams
        uses: rtCamp/action-slack-notify@v2.0
        with:
          status: Deployment successful
          channel: #microsoft-teams-channel